[workspace]
members = ["dronecode", "runner","gui","architecture", "protocol", "profiler", "basestation"]
default-members = ["dronecode"]

[profile.release]
opt-level = "z"
lto = true

[profile.dev]
opt-level = "z"
